export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'
export const UI_SET_LOGIN_ERROR = 'UI_SET_LOGIN_ERROR'
export const IS_SIGNUP = 'IS_SIGNUP'
export const SET_AUTH = 'SET_AUTH'
export const SET_USERS = 'SET_USERS'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const GET_MESSAGES = 'GET_MESSAGES'
export const SET_PENDING_MESSAGE = 'SET_PENDING_MESSAGE'
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'


